[project]
name = "repl-nix-climbingtracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "pillow>=11.0.0",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.36",
    "svgwrite>=1.4.3",
    "flask-wtf>=1.2.2",
    "wtforms>=3.2.1",
    "flask-migrate>=4.0.7",
    "werkzeug>=3.1.3",
    "oauthlib>=3.2.2",
]
